name: LAPRAS Card

# on:
#   workflow_dispatch:
#   schedule:
#     - cron: "0 0 * * *"

jobs:
  update-card:
    name: LAPRAS Card
    runs-on: ubuntu-latest
    steps:
      - uses: kawamataryo/lapras-card-readme@main
        with:
          SHARE_ID: AFWLVCK
          ICON_FIRST: "#203874"
          ICON_SECOND: "#28209d"
          BACKGROUND_FIRST: "#0c132c"
          BACKGROUND_SECOND: "#2e6799"
          LANG: "en"